#!/bin/bash -e
# Build package 'bash' from source
# For Calmira 1.2a2.1 GNU/Linux-libre
# Copyright (C) 2021, 2022 Michail Krasnov <linuxoid85@gmail.com>

NAME="bash"
VERSION="5.1.16"

cd /usr/src/$NAME-$VERSION

./configure --prefix=/usr                   \
            --build=$(support/config.guess) \
            --host=$LFS_TGT                 \
            --without-bash-malloc

make
make DESTDIR=$LFS install

mv $LFS/usr/bin/bash $LFS/bin/bash
ln -sv bash $LFS/bin/sh
