#!/bin/bash -e
# Build package 'binutils' from source
# For Calmira 1.2a2.1 GNU/Linux-libre
# Copyright (C) 2021, 2022 Michail Krasnov <linuxoid85@gmail.com>

NAME="binutils"
VERSION="2.38"

cd /usr/src/$NAME-$VERSION

mkdir build
cd build

../configure --prefix=$LFS/tools \
             --with-sysroot=$LFS \
             --target=$LFS_TGT   \
             --disable-nls       \
             --disable-werror

make
make install
