#!/bin/bash -e
# Build package 'diffutils' from source
# For Calmira 1.2a2.1 GNU/Linux-libre
# Copyright (C) 2021, 2022 Michail Krasnov <linuxoid85@gmail.com>

NAME="diffutils"
VERSION="3.8"

cd /usr/src/$NAME-$VERSION

./configure --prefix=/usr --host=$LFS_TGT

make
make DESTDIR=$LFS install
