#!/bin/bash -e
# Build package 'tar' from source
# For Calmira 1.2a2.1 GNU/Linux-libre
# Copyright (C) 2021, 2022 Michail Krasnov <linuxoid85@gmail.com>

NAME="tar"
VERSION="1.34"

cd /usr/src/$NAME-$VERSION

./configure --prefix=/usr                     \
            --host=$LFS_TGT                   \
            --build=$(build-aux/config.guess) \
            --bindir=/bin

make
make DESTDIR=$LFS install
