#!/bin/bash -e
# Build package 'python' from source
# For Calmira 1.2a2.1 GNU/Linux-libre
# Copyright (C) 2021, 2022 Michail Krasnov <linuxoid85@gmail.com>

NAME="python"
VERSION="3.10.4"

cd /usr/src/$NAME-$VERSION

./configure --prefix=/usr   \
            --enable-shared \
            --without-ensurepip

make
make install
