#!/bin/bash -e
# Build package 'autoconf' from source
# For Calmira 1.2a2.1 GNU/Linux-libre
# Copyright (C) 2021, 2022 Michail Krasnov <linuxoid85@gmail.com>

NAME="autoconf"
VERSION="2.71"

cd /usr/src/$NAME-$VERSION

./configure --prefix=/usr

make
make install
