#!/bin/bash -e
# Build package 'bc' from source
# For Calmira 1.2a2.1 GNU/Linux-libre
# Copyright (C) 2021, 2022 Michail Krasnov <linuxoid85@gmail.com>

NAME="bc"
VERSION="5.2.5"

cd /usr/src/$NAME-$VERSION

CC=gcc ./configure --prefix=/usr -G -O3

make
make install
