#!/bin/bash -e
# Build package 'botscripts' from source
# For Calmira 1.2a2.1 GNU/Linux-libre
# Copyright (C) 2021, 2022 Michail Krasnov <linuxoid85@gmail.com>

NAME="botscripts"
VERSION="1.2a2"

cd /usr/src/$NAME-$VERSION

make install
