#!/bin/bash -e
# Build package 'check' from source
# For Calmira 1.2a2.1 GNU/Linux-libre
# Copyright (C) 2021, 2022 Michail Krasnov <linuxoid85@gmail.com>

NAME="check"
VERSION="0.15.2"

cd /usr/src/$NAME-$VERSION

./configure --prefix=/usr --disable-static

make
make docdir=/usr/share/doc/check-$VERSION install
