#!/bin/bash -e
# Build package 'efivar' from source
# For Calmira 1.2a2.1 GNU/Linux-libre
# Copyright (C) 2021, 2022 Michail Krasnov <linuxoid85@gmail.com>

NAME="efivar"
VERSION="38"

cd /usr/src/$NAME-$VERSION

sed '/prep :/a\\ttouch prep' -i src/Makefile

make
make install LIBDIR=/lib
