#!/bin/bash -e
# Build package 'expat' from source
# For Calmira 1.2a2.1 GNU/Linux-libre
# Copyright (C) 2021, 2022 Michail Krasnov <linuxoid85@gmail.com>

NAME="expat"
VERSION="2.4.8"

cd /usr/src/$NAME-$VERSION

./configure --prefix=/usr    \
            --disable-static \
            --docdir=/usr/share/doc/expat-$VERSION

make
make install

install -v -m644 doc/*.{html,css} /usr/share/doc/expat-$VERSION
