#!/bin/bash -e
# Build package 'file' from source
# For Calmira 1.2a2.1 GNU/Linux-libre
# Copyright (C) 2021, 2022 Michail Krasnov <linuxoid85@gmail.com>

NAME="file"
VERSION="5.41"

cd /usr/src/$NAME-$VERSION

./configure --prefix=/usr

make
make install
