#!/bin/bash -e
# Build package 'gawk' from source
# For Calmira 1.2a2.1 GNU/Linux-libre
# Copyright (C) 2021, 2022 Michail Krasnov <linuxoid85@gmail.com>

NAME="gawk"
VERSION="5.1.1"

cd /usr/src/$NAME-$VERSION

sed -i 's/extras//' Makefile.in
./configure --prefix=/usr

make
make install

mkdir -pv                                   /usr/share/doc/gawk-$VERSION
cp    -v doc/{awkforai.txt,*.{eps,pdf,jpg}} /usr/share/doc/gawk-$VERSION
