#!/bin/bash -e
# Build package 'gcc' from source
# For Calmira 1.2a2.1 GNU/Linux-libre
# Copyright (C) 2021, 2022 Michail Krasnov <linuxoid85@gmail.com>

NAME="gcc"
VERSION="12.1.0"

cd /usr/src/$NAME-$VERSION

case $(uname -m) in
  x86_64)
    sed -e '/m64=/s/lib64/lib/' \
        -i.orig gcc/config/i386/t-linux64
  ;;
esac

mkdir -v build
cd build

../configure --prefix=/usr            \
             LD=ld                    \
             --enable-languages=c,c++ \
             --disable-multilib       \
             --disable-bootstrap      \
             --with-system-zlib

make
make install

chown -v -R root:root \
    /usr/lib/gcc/$(gcc -dumpmachine)/$VERSION/include{,-fixed}

ln -svr /usr/bin/cpp /lib

ln -sfv ../../libexec/gcc/$(gcc -dumpmachine)/$VERSION/liblto_plugin.so \
        /usr/lib/bfd-plugins/

for i in 1 2 3; do
    echo -e "\a\a\a"
    sleep 3
    echo -e "\033[1m\033[5m\033[32mGCC testing will be performed now!\033[0m"
done

function warning() {
    for i in 1 2 3; do
        echo -e "\a"
        sleep 3
        echo "Next test..."
    done
}

echo 'int main(){}' > dummy.c
cc dummy.c -v -Wl,--verbose &> dummy.log

readelf -l a.out | grep ': /lib'
warning

grep -o '/usr/lib.*/crt[1in].*succeeded' dummy.log
warning

grep -B4 '^ /usr/include' dummy.log
warning

grep 'SEARCH.*/usr/lib' dummy.log |sed 's|; |\n|g'
warning

grep "/lib.*/libc.so.6 " dummy.log
warning

grep found dummy.log
warning

echo -e "\a\e[1mEnd of tests!\e[0m"
rm -v dummy.c a.out dummy.log

mkdir -pv /usr/share/gdb/auto-load/usr/lib
mv -v /usr/lib/*gdb.py /usr/share/gdb/auto-load/usr/lib
