#!/bin/bash -e
# Build package 'gdbm' from source
# For Calmira 1.2a2.1 GNU/Linux-libre
# Copyright (C) 2021, 2022 Michail Krasnov <linuxoid85@gmail.com>

NAME="gdbm"
VERSION="1.23"

cd /usr/src/$NAME-$VERSION

./configure --prefix=/usr    \
            --disable-static \
            --enable-libgdbm-compat

make
make install
