#!/bin/bash -e
# Build package 'gperf' from source
# For Calmira 1.2a2.1 GNU/Linux-libre
# Copyright (C) 2021, 2022 Michail Krasnov <linuxoid85@gmail.com>

NAME="gperf"
VERSION="3.1"

cd /usr/src/$NAME-$VERSION

./configure --prefix=/usr --docdir=/usr/share/doc/gperf-$VERSION

make
make install
