#!/bin/bash -e
# Build package 'grep' from source
# For Calmira 1.2a2.1 GNU/Linux-libre
# Copyright (C) 2021, 2022 Michail Krasnov <linuxoid85@gmail.com>

NAME="grep"
VERSION="3.7"

cd /usr/src/$NAME-$VERSION

./configure --prefix=/usr --bindir=/bin

make
make install
