#!/bin/bash -e
# Build package 'groff' from source
# For Calmira 1.2a2.1 GNU/Linux-libre
# Copyright (C) 2021, 2022 Michail Krasnov <linuxoid85@gmail.com>

NAME="groff"
VERSION="1.22.4"

cd /usr/src/$NAME-$VERSION

PAGE=A4 ./configure --prefix=/usr

make -j1
make install
