#!/bin/bash -e
# Build package 'iana-etc' from source
# For Calmira 1.2a2.1 GNU/Linux-libre
# Copyright (C) 2021, 2022 Michail Krasnov <linuxoid85@gmail.com>

NAME="iana-etc"
VERSION="20220524"

cd /usr/src/$NAME-$VERSION

cp services protocols /etc -v
