#!/bin/bash -e
# Build package 'kbd' from source
# For Calmira 1.2a2.1 GNU/Linux-libre
# Copyright (C) 2021, 2022 Michail Krasnov <linuxoid85@gmail.com>

NAME="kbd"
VERSION="2.4.0"

cd /usr/src/$NAME-$VERSION

patch -Np1 -i ../kbd-$VERSION-backspace-1.patch

sed -i '/RESIZECONS_PROGS=/s/yes/no/' configure
sed -i 's/resizecons.8 //' docs/man/man8/Makefile.in

./configure --prefix=/usr --disable-vlock

make
make install

mkdir -pv           /usr/share/doc/kbd-$VERSION
cp -R -v docs/doc/* /usr/share/doc/kbd-$VERSION
