#!/bin/bash -e
# Build package 'kmod' from source
# For Calmira 1.2a2.1 GNU/Linux-libre
# Copyright (C) 2021, 2022 Michail Krasnov <linuxoid85@gmail.com>

NAME="kmod"
VERSION="29"

cd /usr/src/$NAME-$VERSION

./configure --prefix=/usr          \
            --bindir=/bin          \
            --sysconfdir=/etc      \
            --with-rootlibdir=/lib \
            --with-openssl         \
            --with-xz              \
            --with-zstd            \
            --with-zlib

make

make install
for target in depmod insmod lsmod modinfo modprobe rmmod; do
  ln -sfv /bin/kmod /sbin/$target
done

ln -sfv kmod /bin/lsmod
