#!/bin/bash -e
# Build package 'less' from source
# For Calmira 1.2a2.1 GNU/Linux-libre
# Copyright (C) 2021, 2022 Michail Krasnov <linuxoid85@gmail.com>

NAME="less"
VERSION="590"

cd /usr/src/$NAME-$VERSION

./configure --prefix=/usr --sysconfdir=/etc

make
make install
