#!/bin/bash -e
# Build package 'libpipeline' from source
# For Calmira 1.2a2.1 GNU/Linux-libre
# Copyright (C) 2021, 2022 Michail Krasnov <linuxoid85@gmail.com>

NAME="libpipeline"
VERSION="1.5.6"

cd /usr/src/$NAME-$VERSION

./configure --prefix=/usr

make
make install
