#!/bin/bash -e
# Build package 'linux' from source
# For Calmira 1.2a2.1 GNU/Linux-libre
# Copyright (C) 2021, 2022 Michail Krasnov <linuxoid85@gmail.com>

NAME="linux"
VERSION="5.18.1"

cd /usr/src/$NAME-$VERSION

make mrproper
# Считается, что нужный файл 'config' уже присутствует в архиве с исходным кодом
# ядра Linux-libre
make
make modules_install

cp -iv arch/x86/boot/bzImage /boot/vmlinuz-$VERSION
cp -iv System.map /boot/System.map-$VERSION
cp -iv .config /boot/config-$VERSION
ln -svf vmlinuz-$VERSION /boot/vmlinuz
