#!/bin/bash -e
# Build package 'man-pages' from source
# For Calmira 1.2a2.1 GNU/Linux-libre
# Copyright (C) 2021, 2022 Michail Krasnov <linuxoid85@gmail.com>

NAME="man-pages"
VERSION="5.13"

cd /usr/src/$NAME-$VERSION

make prefix=/usr install
