#!/bin/bash -e
# Build package 'mpc' from source
# For Calmira 1.2a2.1 GNU/Linux-libre
# Copyright (C) 2021, 2022 Michail Krasnov <linuxoid85@gmail.com>

NAME="mpc"
VERSION="1.2.1"

cd /usr/src/$NAME-$VERSION

./configure --prefix=/usr    \
            --disable-static \
            --docdir=/usr/share/doc/mpc-$VERSION

make
make html

make install
make install-html
