#!/bin/bash -e
# Build package 'mpfr' from source
# For Calmira 1.2a2.1 GNU/Linux-libre
# Copyright (C) 2021, 2022 Michail Krasnov <linuxoid85@gmail.com>

NAME="mpfr"
VERSION="4.1.0"

cd /usr/src/$NAME-$VERSION

./configure --prefix=/usr        \
            --disable-static     \
            --enable-thread-safe \
            --docdir=/usr/share/doc/mpfr-$VERSION

make
make html

make install
make install-html
