#!/bin/bash -e
# Build package 'pkg-config' from source
# For Calmira 1.2a2.1 GNU/Linux-libre
# Copyright (C) 2021, 2022 Michail Krasnov <linuxoid85@gmail.com>

NAME="pkg-config"
VERSION="0.29.2"

cd /usr/src/$NAME-$VERSION

./configure --prefix=/usr              \
            --with-internal-glib       \
            --disable-host-tool        \
            --docdir=/usr/share/doc/pkg-config-$VERSION

make
make install
