#!/bin/bash -e
# Build package 'popt' from source
# For Calmira 1.2a2.1 GNU/Linux-libre
# Copyright (C) 2021, 2022 Michail Krasnov <linuxoid85@gmail.com>

NAME="popt"
VERSION="1.18"

cd /usr/src/$NAME-$VERSION

./configure --prefix=/usr --disable-static

make
make install
