#!/bin/bash -e
# Build package 'procps-ng' from source
# For Calmira 1.2a2.1 GNU/Linux-libre
# Copyright (C) 2021, 2022 Michail Krasnov <linuxoid85@gmail.com>

NAME="procps-ng"
VERSION="4.0.0"

cd /usr/src/$NAME-$VERSION

./configure --prefix=/usr                              \
            --libdir=/usr/lib                          \
            --docdir=/usr/share/doc/procps-ng-$VERSION \
            --disable-static                           \
            --disable-kill

make
make install

mv -v /usr/lib/libprocps.so.* /lib
ln -sfv ../../lib/$(readlink /usr/lib/libprocps.so) /usr/lib/libprocps
