#!/bin/bash -e
# Build package 'psmisc' from source
# For Calmira 1.2a2.1 GNU/Linux-libre
# Copyright (C) 2021, 2022 Michail Krasnov <linuxoid85@gmail.com>

NAME="psmisc"
VERSION="23.5"

cd /usr/src/$NAME-$VERSION

./configure --prefix=/usr

make
make install

mv -v /usr/bin/fuser   /bin
mv -v /usr/bin/killall /bin
