#!/bin/bash -e
# Build package 'xml-parser' from source
# For Calmira 1.2a2.1 GNU/Linux-libre
# Copyright (C) 2021, 2022 Michail Krasnov <linuxoid85@gmail.com>

NAME="XML-Parser"
VERSION="2.46"

cd /usr/src/$NAME-$VERSION

perl Makefile.PL

make
make install
