#!/bin/bash -e
# Build package 'xz' from source
# For Calmira 1.2a2.1 GNU/Linux-libre
# Copyright (C) 2021, 2022 Michail Krasnov <linuxoid85@gmail.com>

NAME="xz"
VERSION="5.2.5"

cd /usr/src/$NAME-$VERSION

patch -Np1 -i ../xz-$VERSION-upstream_fix-1.patch

./configure --prefix=/usr    \
            --disable-static \
            --docdir=/usr/share/doc/xz-$VERSION

make
make install

mv -v   /usr/bin/{lzma,unlzma,lzcat,xz,unxz,xzcat} /bin
mv -v /usr/lib/liblzma.so.* /lib
ln -svf ../../lib/$(readlink /usr/lib/liblzma.so) /usr/lib/liblzma.so
