#!/bin/bash -e
# Build package 'zstd' from source
# For Calmira 1.2a2.1 GNU/Linux-libre
# Copyright (C) 2021, 2022 Michail Krasnov <linuxoid85@gmail.com>

NAME="zstd"
VERSION="1.5.2"

cd /usr/src/$NAME-$VERSION

patch -Np1 -i ../zstd-$VERSION-upstream_fixes-1.patch

make prefix=/usr
make prefix=/usr install

rm -v /usr/lib/libzstd.a
mv -v /usr/lib/libzstd.so.* /lib
ln -sfv ../../lib/$(readlink /usr/lib/libzstd.so) /usr/lib/libzstd.so
